// Code generated by downloader.go; DO NOT EDIT. 
package ig_ng

import "github.com/Tnze/go-mc/chat"

func init() { chat.SetLanguage(Map) }

var Map = map[string]string{"gui.back":"Azụ", "gui.cancel":"Kwụsị", "gui.done":"Emela", "language.code":"ig_ng", "language.name":"Igbo", "language.region":"Naigeria"}
